gate mcphase_5895416592(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cp(pi/128) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(-pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
}
gate c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  U(pi/2, 0, pi) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_8;
  mcphase_5895416592(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_7;
  x _gate_q_8;
  c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  x _gate_q_0;
  x _gate_q_1;
  x _gate_q_7;
  x _gate_q_8;
}
gate cu1_5895406752(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
}
gate cu1_5895420912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895410208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895408864(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895411552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895417312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895416688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895420096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895412944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895415824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895418944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243536(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247760(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246608(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243104(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249728(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248576(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255152(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242672(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254864(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249248(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256304(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895258080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245408(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250160(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895253184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247232(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895243056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895241808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246656(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244064(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252848(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895247952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245600(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895252560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250112(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895248048(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251936(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245216(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895251504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250448(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895242768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895255968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246896(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895249008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895257744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895256688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895244736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895250352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895254816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895245120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5895246704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676656(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670752(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666480(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675696(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674640(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362668256(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674544(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675168(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362672432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664656(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate mcu1_5895416064(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  cu1_5895406752(pi/128) _gate_q_7, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5895420912(-pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5895406752(pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5895410208(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5895406752(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5895408864(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5895406752(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5895411552(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895406752(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5895417312(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895406752(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5895416688(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895406752(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5895420096(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5895406752(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5895412944(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895415824(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5895418944(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895250064(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5895251024(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895243536(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5895247760(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5895253472(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5895406752(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5895246608(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895243968(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895243104(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895242096(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5895249728(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895253088(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895245504(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895254288(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5895248576(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895253952(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895254768(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895255152(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5895242672(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895247424(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5895244256(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5895254864(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5895406752(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5895254480(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895248720(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895247472(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895247136(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895244304(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895249248(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895255056(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895247568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5895254912(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895244208(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895256112(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895257600(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895256304(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895245936(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895244784(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895258080(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5895245408(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895250160(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895256256(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895253616(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895253184(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895247232(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895243632(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895243056(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5895242336(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895255632(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895250640(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895241808(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5895246656(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895248816(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5895244064(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5895252848(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5895406752(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5895252944(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895249392(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895247952(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895252080(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895242048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245600(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895252800(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257456(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5895252560(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895256832(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895255776(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895250112(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895249200(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257312(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895249776(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257936(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5895248048(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257888(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895251936(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895249920(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895245168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245216(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895251792(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895251504(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5895257792(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895257072(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895250448(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895242768(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895256208(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895255968(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895246896(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895249008(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5895257744(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895256688(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895244736(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895250352(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5895254816(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5895245120(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5895246704(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675504(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5362667680(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362666096(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362676656(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362673488(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669456(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362670752(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675840(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5362664944(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362666480(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362675696(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362674640(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362668256(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675312(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362665136(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362674352(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5362671664(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362676800(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362674544(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675168(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362672432(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362664656(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362669120(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675744(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5895406752(pi/128) _gate_q_0, _gate_q_8;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  h _gate_q_8;
  mcu1_5895416064(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  h _gate_q_8;
}