gate mcphase_5367985840(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7 {
  cp(pi/128) _gate_q_6, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(-pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_6, _gate_q_5;
  cp(pi/128) _gate_q_5, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_5, _gate_q_4;
  cp(-pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_6, _gate_q_4;
  cp(pi/128) _gate_q_4, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_4, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_5, _gate_q_3;
  cp(-pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_6, _gate_q_3;
  cp(pi/128) _gate_q_3, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_3, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_4, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_5, _gate_q_2;
  cp(-pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_6, _gate_q_2;
  cp(pi/128) _gate_q_2, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_2, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_3, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_4, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_5, _gate_q_1;
  cp(-pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_6, _gate_q_1;
  cp(pi/128) _gate_q_1, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_1, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_2, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_3, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_4, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_5, _gate_q_0;
  cp(-pi/128) _gate_q_0, _gate_q_7;
  cx _gate_q_6, _gate_q_0;
  cp(pi/128) _gate_q_0, _gate_q_7;
}
gate c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  U(pi/2, 0, pi) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/4, -pi/2, pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  U(pi/2, pi/4, -3*pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_3, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_8, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, pi/4, -pi) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  p(-pi/4) _gate_q_4;
  cx _gate_q_0, _gate_q_4;
  p(pi/4) _gate_q_4;
  cx _gate_q_1, _gate_q_4;
  U(pi/2, 0, 3*pi/4) _gate_q_4;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  p(-pi/4) _gate_q_5;
  cx _gate_q_2, _gate_q_5;
  p(pi/4) _gate_q_5;
  cx _gate_q_4, _gate_q_5;
  U(pi/2, 0, 3*pi/4) _gate_q_5;
  U(pi/4, pi/2, -pi/2) _gate_q_8;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  U(pi/2, pi/4, -3*pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, -pi/4, 3*pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_7, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_8, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_2;
  U(0, 2.1919811339890787, -2.1919811339890782) _gate_q_3;
  cx _gate_q_5, _gate_q_2;
  p(-pi/4) _gate_q_2;
  cx _gate_q_4, _gate_q_2;
  p(pi/4) _gate_q_2;
  cx _gate_q_5, _gate_q_2;
  U(pi/2, 0, 3*pi/4) _gate_q_2;
  cx _gate_q_2, _gate_q_3;
  p(-pi/4) _gate_q_3;
  cx _gate_q_6, _gate_q_3;
  p(pi/4) _gate_q_3;
  cx _gate_q_2, _gate_q_3;
  U(pi/2, 0, 3*pi/4) _gate_q_3;
  U(pi/2, pi/4, -pi) _gate_q_8;
  mcphase_5367985840(pi/2) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7;
}
gate Oracle _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  x _gate_q_2;
  x _gate_q_3;
  x _gate_q_5;
  c8z _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  x _gate_q_2;
  x _gate_q_3;
  x _gate_q_5;
}
gate cu1_5367979264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
}
gate cu1_5367978736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367977008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367975136(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367979312(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367983920(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367974176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367975808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367975616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367983392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367978784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367987712(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367983776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367976432(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367979456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367972016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367977824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367981664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367980224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367972352(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5367973648(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362678960(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664272(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673824(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674688(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664704(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676416(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670944(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676608(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677328(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667632(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362672192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674832(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665520(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673536(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665376(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670656(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362679584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671616(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677568(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673680(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670128(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362668880(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670992(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677088(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669552(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667776(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671520(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362668928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664560(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677472(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362663888(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664800(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362671184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677952(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666960(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669264(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665904(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665184(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673584(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664080(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362663504(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362663744(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675120(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675456(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362675024(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667968(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362668208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670368(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362678144(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665808(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362679392(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665232(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667488(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362672288(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667200(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362663792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669072(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666720(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362678768(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673008(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666192(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362665856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677664(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669792(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362667344(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362676176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362679728(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362673872(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362678816(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362664320(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362674400(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362669840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362663840(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362666912(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362670176(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362672336(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362677760(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5362672096(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5363761856(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5363766224(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5363762000(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5363776208(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364604016(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364607424(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364598928(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364609056(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364598784(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364600032(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364597296(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate cu1_5364598736(_gate_p_0) _gate_q_0, _gate_q_1 {
  u1(-pi/256) _gate_q_0;
  cx _gate_q_0, _gate_q_1;
  u1(pi/256) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
  u1(-pi/256) _gate_q_1;
}
gate mcu1_5364080976(_gate_p_0) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  cu1_5367979264(pi/128) _gate_q_7, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5367978736(-pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_7, _gate_q_6;
  cu1_5367979264(pi/128) _gate_q_6, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5367977008(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5367979264(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_6, _gate_q_5;
  cu1_5367975136(-pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_7, _gate_q_5;
  cu1_5367979264(pi/128) _gate_q_5, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5367979312(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5367979264(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5367983920(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5367979264(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_5, _gate_q_4;
  cu1_5367974176(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5367979264(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_6, _gate_q_4;
  cu1_5367975808(-pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_7, _gate_q_4;
  cu1_5367979264(pi/128) _gate_q_4, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5367975616(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5367983392(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5367978784(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5367987712(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_4, _gate_q_3;
  cu1_5367983776(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5367976432(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_5, _gate_q_3;
  cu1_5367979456(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_6, _gate_q_3;
  cu1_5367972016(-pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_7, _gate_q_3;
  cu1_5367979264(pi/128) _gate_q_3, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5367977824(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5367981664(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5367980224(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5367972352(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5367973648(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362678960(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5362664272(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362671088(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_3, _gate_q_2;
  cu1_5362673824(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362674736(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5362674688(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362664704(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_4, _gate_q_2;
  cu1_5362676416(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362664032(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_5, _gate_q_2;
  cu1_5362670944(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_6, _gate_q_2;
  cu1_5362671808(-pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_7, _gate_q_2;
  cu1_5367979264(pi/128) _gate_q_2, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5362676608(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362677328(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362667632(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362670560(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5362672192(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362664128(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362674832(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362676224(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5362665520(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362673536(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362674784(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362665376(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5362666000(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362670656(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362679584(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362671616(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_2, _gate_q_1;
  cu1_5362669024(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362677568(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362677184(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362667872(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5362673680(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362670128(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362668880(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362670992(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_3, _gate_q_1;
  cu1_5362677088(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362669552(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362667776(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362671520(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_4, _gate_q_1;
  cu1_5362668928(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362664560(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_5, _gate_q_1;
  cu1_5362677472(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_6, _gate_q_1;
  cu1_5362663888(-pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_7, _gate_q_1;
  cu1_5367979264(pi/128) _gate_q_1, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5362664800(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362671184(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362677952(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362666960(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362669264(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362665904(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362665184(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669744(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5362673584(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362667056(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362664080(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362663504(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362663744(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675120(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362675456(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362675024(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5362667968(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362668208(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362670368(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362678144(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362665808(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362679392(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362665232(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362667488(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5362672288(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362667200(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362673296(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362673344(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362663792(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669072(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362677424(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362666720(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_1, _gate_q_0;
  cu1_5362678768(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362673008(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362666192(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362665856(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362677664(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669792(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362667344(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362676176(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5362679728(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362673872(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362678816(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362664320(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5362674400(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362669840(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362663840(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362666912(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_2, _gate_q_0;
  cu1_5362670176(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362672336(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5362677760(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5362672096(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5363761856(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5363766224(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5363762000(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5363776208(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_3, _gate_q_0;
  cu1_5364604016(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364607424(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364598928(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364609056(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_4, _gate_q_0;
  cu1_5364598784(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364600032(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_5, _gate_q_0;
  cu1_5364597296(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_6, _gate_q_0;
  cu1_5364598736(-pi/128) _gate_q_0, _gate_q_8;
  cx _gate_q_7, _gate_q_0;
  cu1_5367979264(pi/128) _gate_q_0, _gate_q_8;
}
gate mcx _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8 {
  h _gate_q_8;
  mcu1_5364080976(pi) _gate_q_0, _gate_q_1, _gate_q_2, _gate_q_3, _gate_q_4, _gate_q_5, _gate_q_6, _gate_q_7, _gate_q_8;
  h _gate_q_8;
}